-- schema for hvdsa parcel database

CREATE TABLE IF NOT EXISTS hvdsa.parcel (
    acreage_of_parent numeric,
    assessed_value numeric,
    building_assessment numeric,
    capped_value numeric,
    cvt_code text,
    cvt_description text,
    historical_district text,
    homestead_taxable numeric,
    homestea_pct numeric,
    lastupdate numeric,
    legal_description text,
    objectid int,
    owner_care_of text,
    owner_city text,
    owner_country text,
    owner_name text,
    owner_name2 text,
    owner_state text,
    owner_street text,
    owner_zip text,
    parent_parcel_num text,
    pin text,
    prop_city text,
    prop_class text,
    prop_class_description text,
    prop_state text,
    prop_street text,
    prop_street_num text,
    prop_zip text,
    school_district text,
    school_name text,
    sev numeric,
    shape_area numeric,
    shape_len numeric,
    statedarea text,
    status_code text,
    status_desc text,
    taxable_value numeric,
    tax_year numeric,
    txpyrs_care_of text,
    txpyrs_city text,
    txpyrs_country text,
    txpyrs_name text,
    txpyrs_state text,
    txpyrs_street_addr text,
    txpyrs_zip_code text,
    unit_apt_num text,
--    geometry text,
--   latlngcoords text,
    latlngcentroid text
--    numcoords int
);